export const USUARIO_AUTENTICADO  = "USUARIO_AUTENTICADO";
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const LIMPIAR_ERROR = "LIMPIAR_ERROR";

//Autenticacion
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";